language: ruby
rvm: 2.4.1
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - ruby .github/osia_get_links.rb
  - awesome_bot check-unique.txt --allow-ssl -a 302 -w xbmc/xbmc
  - awesome_bot check-links.txt  --allow-ssl -a 403 --allow-dupe
after_script:
  - awesome_bot check-info.txt -a 403
  - danger
